name: "Sprint Stats"
on:
  schedule:
    - cron: '30 23 * * *'
  workflow_dispatch:

env:
    NODE_VERSION: 20.11.0

jobs:
  stats:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v3
        - uses: actions/setup-node@v2
          with:
              node-version: ${{ env.NODE_VERSION }}
              cache: "npm"
        - run: npm ci
        - run: npm run render
          env:
            API_ACCESS_TOKEN: ${{ secrets.API_ACCESS_TOKEN }}
            GH_ORG: safe-global
            GH_ORG_PROJECT_NUMBER: 14
        - run: git config --global user.email "bot@rimeissner.dev"
        - run: git config --global user.name "Stat Bot"
        - run: git commit -am "Automated stat update"
        - run: git push